[tool.poetry]
name = "home-automation"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "home_automation"}]

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.0.327"
speechrecognition = "^3.10.0"
youtube-search-python = "^1.6.6"
pyautogui = "^0.9.54"
openai = "^0.28.1"
pyaudio = "^0.2.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
